export const dummyData = {
  dashboard: [
    { id: 1, name: 'Dashboard Item 1' },
    { id: 2, name: 'Dashboard Item 2' },
  ],
  product: [
    { id: 1, name: 'Product 1', price: 100 },
    { id: 2, name: 'Product 2', price: 200 },
  ],
  user: [
    { id: 1, name: 'User 1', role: 'Admin' },
    { id: 2, name: 'User 2', role: 'Manager' },
  ],
  store: [
    { id: 1, name: 'Store 1', location: 'City A' },
    { id: 2, name: 'Store 2', location: 'City B' },
  ],
  warehouse: [
    { id: 1, name: 'Warehouse 1', capacity: 500 },
    { id: 2, name: 'Warehouse 2', capacity: 1000 },
  ],
  sale: [
    { id: 1, customer: 'Customer 1', total: 300 },
    { id: 2, customer: 'Customer 2', total: 500 },
  ],
  purchase: [
    { id: 1, supplier: 'Supplier 1', total: 400 },
    { id: 2, supplier: 'Supplier 2', total: 600 },
  ],
  pos_sale_customer_list: [
    {
      customer_code: "CUST001",
      name: "John Doe",
      customer_store_name: "Store A",
      phone: "1234567890",
      address: "123 Main St, City A",
      virtual_balance: 100.0,
      vat_number: "VAT12345",
      status: true,
    },
    {
      customer_code: "CUST002",
      name: "Jane Smith",
      customer_store_name: "Store B",
      phone: "9876543210",
      address: "456 Elm St, City B",
      virtual_balance: 200.0,
      vat_number: "VAT67890",
      status: false,
    },
    {
      customer_code: "CUST003",
      name: "Alice Johnson",
      customer_store_name: "Store C",
      phone: "5555555555",
      address: "789 Oak St, City C",
      virtual_balance: 150.0,
      vat_number: "VAT11223",
      status: true,
    },
  ],
  product_management_list: [
    {
      product_name: "Product A",
      arabic_name: "منتج أ",
      specification: "Spec A",
      item_code: "ITEM001",
      purchase_price: 50,
      minimum_selling_price: 60,
      selling_price: 70,
      unit_name: "Unit A",
      status: true,
    },
    {
      product_name: "Product B",
      arabic_name: "منتج ب",
      specification: "Spec B",
      item_code: "ITEM002",
      purchase_price: 40,
      minimum_selling_price: 50,
      selling_price: 60,
      unit_name: "Unit B",
      status: false,
    },
    {
      product_name: "Product C",
      arabic_name: "منتج ج",
      specification: "Spec C",
      item_code: "ITEM003",
      purchase_price: 30,
      minimum_selling_price: 40,
      selling_price: 50,
      unit_name: "Unit C",
      status: true,
    },
  ],
  product_whole_purchase_list: [
    {
      purchase_date_time: "2025-04-30",
      invoice_no: "INV001",
      reference_no: "REF001",
      supplier_name: "Supplier A",
      vat_number: "VAT12345",
      after_discount_amount: 1000,
      total_vat_amount: 150,
      total_amount: 1150,
    },
    {
      purchase_date_time: "2025-04-29",
      invoice_no: "INV002",
      reference_no: "REF002",
      supplier_name: "Supplier B",
      vat_number: "VAT67890",
      after_discount_amount: 2000,
      total_vat_amount: 300,
      total_amount: 2300,
    },
    {
      purchase_date_time: "2025-04-28",
      invoice_no: "INV003",
      reference_no: "REF003",
      supplier_name: "Supplier C",
      vat_number: "VAT11223",
      after_discount_amount: 1500,
      total_vat_amount: 225,
      total_amount: 1725,
    },
  ],
  assign_van_list: [
    {
      start_date_time: "2025-04-30",
      end_date_time: "2025-05-01",
      warehouse_name: "Warehouse A",
      van_name: "Van 1",
      number: "VAN001",
      sales_man_user_name: "John Doe",
      end_status: 0,
    },
    {
      start_date_time: "2025-04-29",
      end_date_time: "2025-04-30",
      warehouse_name: "Warehouse B",
      van_name: "Van 2",
      number: "VAN002",
      sales_man_user_name: "Jane Smith",
      end_status: 1,
    },
    {
      start_date_time: "2025-04-28",
      end_date_time: "2025-04-29",
      warehouse_name: "Warehouse C",
      van_name: "Van 3",
      number: "VAN003",
      sales_man_user_name: "Alice Johnson",
      end_status: 0,
    },
  ],
  stock_transfer_main_list: [
    {
      issue_date: "2025-04-30",
      invoice_no: "INV001",
      total_amount: 1500,
      user_name: "John Doe",
      warehouse_name: "Warehouse A",
      store_name: "Store A",
      sales_man_user_name: "Jane Smith",
      van_name: "Van 1",
    },
    {
      issue_date: "2025-04-29",
      invoice_no: "INV002",
      total_amount: 2000,
      user_name: "Alice Johnson",
      warehouse_name: "Warehouse B",
      store_name: "Store B",
      sales_man_user_name: "Bob Brown",
      van_name: "Van 2",
    },
    {
      issue_date: "2025-04-28",
      invoice_no: "INV003",
      total_amount: 1800,
      user_name: "Charlie Davis",
      warehouse_name: "Warehouse C",
      store_name: "Store C",
      sales_man_user_name: "Diana Evans",
      van_name: "Van 3",
    },
  ],
};

export default dummyData;